[workspace]
members = ["cron", "cronerator"]
resolver = "3"

[workspace.package]
authors = ["Sean Quinlan <quinlan@dagsterlabs.com>"]
edition = "2024"
repository = "https://github.com/dagster-io/cronerator"
license = "MIT OR Apache-2.0"
keywords = ["python"]
categories = []